//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDKAdminService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Place
    {
        [Key]
        [HiddenInput(DisplayValue = false)]
        public string id { get; set; }

        [Required(ErrorMessage ="To pole jest wymagane")]
        [DisplayName("Nazwa")]
        [StringLength(50, ErrorMessage ="Nazwa nie mo¿e przekraczaæ 50 znaków.")]
        [DataType(DataType.Text)]
        public string placeName { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [DisplayName("Opis")]
        [StringLength(500, ErrorMessage = "Nazwa nie mo¿e przekraczaæ 500 znaków.")]
        [DataType(DataType.Text)]
        public string placeDescription { get; set; }

        [Required(ErrorMessage ="Podaj szerokoœæ geograficzn¹ w formacie XX,XXXXXX")]
        [DisplayName("Szerokoœæ")]
        [DisplayFormat(DataFormatString = "{0:##.######}", ApplyFormatInEditMode = true)]
        public decimal latitude { get; set; }

        [Required(ErrorMessage = "Podaj szerokoœæ geograficzn¹ w formacie YY,YYYYYY")]
        [DisplayName("Wysokoœæ")]
        [DisplayFormat(DataFormatString = "{0:##.######}", ApplyFormatInEditMode = true)]
        public decimal longitude { get; set; }

        [Required(ErrorMessage = "To pole jest wymagane")]
        [DisplayName("Adres")]
        public string PlaceAddess { get; set; }

        [HiddenInput(DisplayValue = false)]
        public byte[] version { get; set; }

        [DisplayName("Dodano")]
        public System.DateTimeOffset createdAt { get; set; }

        [DisplayName("Data ostatniej edycji")]
        public System.DateTimeOffset updatedAt { get; set; }
    }
}
